### ISSUE TITLE
Does illumina_adapters_all.fasta have the Nextera adaptors?

### ISSUE THREAD

**Issue by tseemann** [jasonsahl/UGAP#1]
Does `illumina_adapters_all.fasta` have Nextera adaptors in it?

**Comment by jasonsahl** [comment]
Not sure, I never deal with nextera libraries.

**Comment by tseemann** [comment]
If you ever get sequence from MiSeq or NextSeq (and soon HiSeq) they will have used Nextera rather than TruSeq. With luck, they will be pre-removed by the Illumina base caller, but often not. Will screw up your assemblies.

Here's the trimmomatic file for them:

```
>PrefixNX/1
AGATGTGTATAAGAGACAG
>PrefixNX/2
AGATGTGTATAAGAGACAG
>Trans1
TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
>Trans1_rc
CTGTCTCTTATACACATCTGACGCTGCCGACGA
>Trans2
GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
>Trans2_rc
CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
```

**Comment by jasonsahl** [comment]
Thanks, I added in the ones that weren't there already.
